using System;

namespace SpirV;

[Flags]
public enum ImageOperands : uint
{
	None = 0,
	Bias = 1,
	Lod = 2,
	Grad = 4,
	ConstOffset = 8,
	Offset = 16,
	ConstOffsets = 32,
	Sample = 64,
	MinLod = 128,
}
[Flags]
public enum FPFastMathMode : uint
{
	None = 0,
	NotNaN = 1,
	NotInf = 2,
	NSZ = 4,
	AllowRecip = 8,
	Fast = 16,
}
[Flags]
public enum SelectionControl : uint
{
	None = 0,
	Flatten = 1,
	DontFlatten = 2,
}
[Flags]
public enum LoopControl : uint
{
	None = 0,
	Unroll = 1,
	DontUnroll = 2,
	DependencyInfinite = 4,
	DependencyLength = 8,
}
[Flags]
public enum FunctionControl : uint
{
	None = 0,
	Inline = 1,
	DontInline = 2,
	Pure = 4,
	Const = 8,
}
[Flags]
public enum MemorySemantics : uint
{
	Relaxed = 0,
	None = 0,
	Acquire = 2,
	Release = 4,
	AcquireRelease = 8,
	SequentiallyConsistent = 16,
	UniformMemory = 64,
	SubgroupMemory = 128,
	WorkgroupMemory = 256,
	CrossWorkgroupMemory = 512,
	AtomicCounterMemory = 1024,
	ImageMemory = 2048,
}
[Flags]
public enum MemoryAccess : uint
{
	None = 0,
	Volatile = 1,
	Aligned = 2,
	Nontemporal = 4,
}
[Flags]
public enum KernelProfilingInfo : uint
{
	None = 0,
	CmdExecTime = 1,
}
public enum SourceLanguage : uint
{
	Unknown = 0,
	ESSL = 1,
	GLSL = 2,
	OpenCL_C = 3,
	OpenCL_CPP = 4,
	HLSL = 5,
}
public enum ExecutionModel : uint
{
	Vertex = 0,
	TessellationControl = 1,
	TessellationEvaluation = 2,
	Geometry = 3,
	Fragment = 4,
	GLCompute = 5,
	Kernel = 6,
}
public enum AddressingModel : uint
{
	Logical = 0,
	Physical32 = 1,
	Physical64 = 2,
}
public enum MemoryModel : uint
{
	Simple = 0,
	GLSL450 = 1,
	OpenCL = 2,
}
public enum ExecutionMode : uint
{
	Invocations = 0,
	SpacingEqual = 1,
	SpacingFractionalEven = 2,
	SpacingFractionalOdd = 3,
	VertexOrderCw = 4,
	VertexOrderCcw = 5,
	PixelCenterInteger = 6,
	OriginUpperLeft = 7,
	OriginLowerLeft = 8,
	EarlyFragmentTests = 9,
	PointMode = 10,
	Xfb = 11,
	DepthReplacing = 12,
	DepthGreater = 14,
	DepthLess = 15,
	DepthUnchanged = 16,
	LocalSize = 17,
	LocalSizeHint = 18,
	InputPoints = 19,
	InputLines = 20,
	InputLinesAdjacency = 21,
	Triangles = 22,
	InputTrianglesAdjacency = 23,
	Quads = 24,
	Isolines = 25,
	OutputVertices = 26,
	OutputPoints = 27,
	OutputLineStrip = 28,
	OutputTriangleStrip = 29,
	VecTypeHint = 30,
	ContractionOff = 31,
	Initializer = 33,
	Finalizer = 34,
	SubgroupSize = 35,
	SubgroupsPerWorkgroup = 36,
	SubgroupsPerWorkgroupId = 37,
	LocalSizeId = 38,
	LocalSizeHintId = 39,
	PostDepthCoverage = 4446,
	StencilRefReplacingEXT = 5027,
}
public enum StorageClass : uint
{
	UniformConstant = 0,
	Input = 1,
	Uniform = 2,
	Output = 3,
	Workgroup = 4,
	CrossWorkgroup = 5,
	Private = 6,
	Function = 7,
	Generic = 8,
	PushConstant = 9,
	AtomicCounter = 10,
	Image = 11,
	StorageBuffer = 12,
}
public enum Dim : uint
{
	Dim1D = 0,
	Dim2D = 1,
	Dim3D = 2,
	Cube = 3,
	Rect = 4,
	Buffer = 5,
	SubpassData = 6,
}
public enum SamplerAddressingMode : uint
{
	None = 0,
	ClampToEdge = 1,
	Clamp = 2,
	Repeat = 3,
	RepeatMirrored = 4,
}
public enum SamplerFilterMode : uint
{
	Nearest = 0,
	Linear = 1,
}
public enum ImageFormat : uint
{
	Unknown = 0,
	Rgba32f = 1,
	Rgba16f = 2,
	R32f = 3,
	Rgba8 = 4,
	Rgba8Snorm = 5,
	Rg32f = 6,
	Rg16f = 7,
	R11fG11fB10f = 8,
	R16f = 9,
	Rgba16 = 10,
	Rgb10A2 = 11,
	Rg16 = 12,
	Rg8 = 13,
	R16 = 14,
	R8 = 15,
	Rgba16Snorm = 16,
	Rg16Snorm = 17,
	Rg8Snorm = 18,
	R16Snorm = 19,
	R8Snorm = 20,
	Rgba32i = 21,
	Rgba16i = 22,
	Rgba8i = 23,
	R32i = 24,
	Rg32i = 25,
	Rg16i = 26,
	Rg8i = 27,
	R16i = 28,
	R8i = 29,
	Rgba32ui = 30,
	Rgba16ui = 31,
	Rgba8ui = 32,
	R32ui = 33,
	Rgb10a2ui = 34,
	Rg32ui = 35,
	Rg16ui = 36,
	Rg8ui = 37,
	R16ui = 38,
	R8ui = 39,
}
public enum ImageChannelOrder : uint
{
	R = 0,
	A = 1,
	RG = 2,
	RA = 3,
	RGB = 4,
	RGBA = 5,
	BGRA = 6,
	ARGB = 7,
	Intensity = 8,
	Luminance = 9,
	Rx = 10,
	RGx = 11,
	RGBx = 12,
	Depth = 13,
	DepthStencil = 14,
	sRGB = 15,
	sRGBx = 16,
	sRGBA = 17,
	sBGRA = 18,
	ABGR = 19,
}
public enum ImageChannelDataType : uint
{
	SnormInt8 = 0,
	SnormInt16 = 1,
	UnormInt8 = 2,
	UnormInt16 = 3,
	UnormShort565 = 4,
	UnormShort555 = 5,
	UnormInt101010 = 6,
	SignedInt8 = 7,
	SignedInt16 = 8,
	SignedInt32 = 9,
	UnsignedInt8 = 10,
	UnsignedInt16 = 11,
	UnsignedInt32 = 12,
	HalfFloat = 13,
	Float = 14,
	UnormInt24 = 15,
	UnormInt101010_2 = 16,
}
public enum FPRoundingMode : uint
{
	RTE = 0,
	RTZ = 1,
	RTP = 2,
	RTN = 3,
}
public enum LinkageType : uint
{
	Export = 0,
	Import = 1,
}
public enum AccessQualifier : uint
{
	ReadOnly = 0,
	WriteOnly = 1,
	ReadWrite = 2,
}
public enum FunctionParameterAttribute : uint
{
	Zext = 0,
	Sext = 1,
	ByVal = 2,
	Sret = 3,
	NoAlias = 4,
	NoCapture = 5,
	NoWrite = 6,
	NoReadWrite = 7,
}
public enum Decoration : uint
{
	RelaxedPrecision = 0,
	SpecId = 1,
	Block = 2,
	BufferBlock = 3,
	RowMajor = 4,
	ColMajor = 5,
	ArrayStride = 6,
	MatrixStride = 7,
	GLSLShared = 8,
	GLSLPacked = 9,
	CPacked = 10,
	BuiltIn = 11,
	NoPerspective = 13,
	Flat = 14,
	Patch = 15,
	Centroid = 16,
	Sample = 17,
	Invariant = 18,
	Restrict = 19,
	Aliased = 20,
	Volatile = 21,
	Constant = 22,
	Coherent = 23,
	NonWritable = 24,
	NonReadable = 25,
	Uniform = 26,
	SaturatedConversion = 28,
	Stream = 29,
	Location = 30,
	Component = 31,
	Index = 32,
	Binding = 33,
	DescriptorSet = 34,
	Offset = 35,
	XfbBuffer = 36,
	XfbStride = 37,
	FuncParamAttr = 38,
	FPRoundingMode = 39,
	FPFastMathMode = 40,
	LinkageAttributes = 41,
	NoContraction = 42,
	InputAttachmentIndex = 43,
	Alignment = 44,
	MaxByteOffset = 45,
	AlignmentId = 46,
	MaxByteOffsetId = 47,
	ExplicitInterpAMD = 4999,
	OverrideCoverageNV = 5248,
	PassthroughNV = 5250,
	ViewportRelativeNV = 5252,
	SecondaryViewportRelativeNV = 5256,
	HlslCounterBufferGOOGLE = 5634,
	HlslSemanticGOOGLE = 5635,
}
public enum BuiltIn : uint
{
	Position = 0,
	PointSize = 1,
	ClipDistance = 3,
	CullDistance = 4,
	VertexId = 5,
	InstanceId = 6,
	PrimitiveId = 7,
	InvocationId = 8,
	Layer = 9,
	ViewportIndex = 10,
	TessLevelOuter = 11,
	TessLevelInner = 12,
	TessCoord = 13,
	PatchVertices = 14,
	FragCoord = 15,
	PointCoord = 16,
	FrontFacing = 17,
	SampleId = 18,
	SamplePosition = 19,
	SampleMask = 20,
	FragDepth = 22,
	HelperInvocation = 23,
	NumWorkgroups = 24,
	WorkgroupSize = 25,
	WorkgroupId = 26,
	LocalInvocationId = 27,
	GlobalInvocationId = 28,
	LocalInvocationIndex = 29,
	WorkDim = 30,
	GlobalSize = 31,
	EnqueuedWorkgroupSize = 32,
	GlobalOffset = 33,
	GlobalLinearId = 34,
	SubgroupSize = 36,
	SubgroupMaxSize = 37,
	NumSubgroups = 38,
	NumEnqueuedSubgroups = 39,
	SubgroupId = 40,
	SubgroupLocalInvocationId = 41,
	VertexIndex = 42,
	InstanceIndex = 43,
	SubgroupEqMaskKHR = 4416,
	SubgroupGeMaskKHR = 4417,
	SubgroupGtMaskKHR = 4418,
	SubgroupLeMaskKHR = 4419,
	SubgroupLtMaskKHR = 4420,
	BaseVertex = 4424,
	BaseInstance = 4425,
	DrawIndex = 4426,
	DeviceIndex = 4438,
	ViewIndex = 4440,
	BaryCoordNoPerspAMD = 4992,
	BaryCoordNoPerspCentroidAMD = 4993,
	BaryCoordNoPerspSampleAMD = 4994,
	BaryCoordSmoothAMD = 4995,
	BaryCoordSmoothCentroidAMD = 4996,
	BaryCoordSmoothSampleAMD = 4997,
	BaryCoordPullModelAMD = 4998,
	FragStencilRefEXT = 5014,
	ViewportMaskNV = 5253,
	SecondaryPositionNV = 5257,
	SecondaryViewportMaskNV = 5258,
	PositionPerViewNV = 5261,
	ViewportMaskPerViewNV = 5262,
}
public enum Scope : uint
{
	CrossDevice = 0,
	Device = 1,
	Workgroup = 2,
	Subgroup = 3,
	Invocation = 4,
}
public enum GroupOperation : uint
{
	Reduce = 0,
	InclusiveScan = 1,
	ExclusiveScan = 2,
}
public enum KernelEnqueueFlags : uint
{
	NoWait = 0,
	WaitKernel = 1,
	WaitWorkGroup = 2,
}
public enum Capability : uint
{
	Matrix = 0,
	Shader = 1,
	Geometry = 2,
	Tessellation = 3,
	Addresses = 4,
	Linkage = 5,
	Kernel = 6,
	Vector16 = 7,
	Float16Buffer = 8,
	Float16 = 9,
	Float64 = 10,
	Int64 = 11,
	Int64Atomics = 12,
	ImageBasic = 13,
	ImageReadWrite = 14,
	ImageMipmap = 15,
	Pipes = 17,
	Groups = 18,
	DeviceEnqueue = 19,
	LiteralSampler = 20,
	AtomicStorage = 21,
	Int16 = 22,
	TessellationPointSize = 23,
	GeometryPointSize = 24,
	ImageGatherExtended = 25,
	StorageImageMultisample = 27,
	UniformBufferArrayDynamicIndexing = 28,
	SampledImageArrayDynamicIndexing = 29,
	StorageBufferArrayDynamicIndexing = 30,
	StorageImageArrayDynamicIndexing = 31,
	ClipDistance = 32,
	CullDistance = 33,
	ImageCubeArray = 34,
	SampleRateShading = 35,
	ImageRect = 36,
	SampledRect = 37,
	GenericPointer = 38,
	Int8 = 39,
	InputAttachment = 40,
	SparseResidency = 41,
	MinLod = 42,
	Sampled1D = 43,
	Image1D = 44,
	SampledCubeArray = 45,
	SampledBuffer = 46,
	ImageBuffer = 47,
	ImageMSArray = 48,
	StorageImageExtendedFormats = 49,
	ImageQuery = 50,
	DerivativeControl = 51,
	InterpolationFunction = 52,
	TransformFeedback = 53,
	GeometryStreams = 54,
	StorageImageReadWithoutFormat = 55,
	StorageImageWriteWithoutFormat = 56,
	MultiViewport = 57,
	SubgroupDispatch = 58,
	NamedBarrier = 59,
	PipeStorage = 60,
	SubgroupBallotKHR = 4423,
	DrawParameters = 4427,
	SubgroupVoteKHR = 4431,
	StorageBuffer16BitAccess = 4433,
	StorageUniformBufferBlock16 = 4433,
	UniformAndStorageBuffer16BitAccess = 4434,
	StorageUniform16 = 4434,
	StoragePushConstant16 = 4435,
	StorageInputOutput16 = 4436,
	DeviceGroup = 4437,
	MultiView = 4439,
	VariablePointersStorageBuffer = 4441,
	VariablePointers = 4442,
	AtomicStorageOps = 4445,
	SampleMaskPostDepthCoverage = 4447,
	ImageGatherBiasLodAMD = 5009,
	FragmentMaskAMD = 5010,
	StencilExportEXT = 5013,
	ImageReadWriteLodAMD = 5015,
	SampleMaskOverrideCoverageNV = 5249,
	GeometryShaderPassthroughNV = 5251,
	ShaderViewportIndexLayerEXT = 5254,
	ShaderViewportIndexLayerNV = 5254,
	ShaderViewportMaskNV = 5255,
	ShaderStereoViewNV = 5259,
	PerViewAttributesNV = 5260,
	SubgroupShuffleINTEL = 5568,
	SubgroupBufferBlockIOINTEL = 5569,
	SubgroupImageBlockIOINTEL = 5570,
}